image: node:12.16.3

stages:
  - publish

publish:
  stage: publish
  only:
    - master
  script:
    - npm ci
    # git config for committing and pushing
    - git remote set-url origin https://${GIT_USER_NAME}:${GIT_USER_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git config --global user.email "${GIT_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME}"
    # npm config for publishing
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' >> .npmrc
    - echo '//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}' >> .npmrc
    - echo '@buildigo.org:registry=https://gitlab.com/api/v4/packages/npm/' >> .npmrc
    - cat .npmrc
    # tag, push and publish
    - npm run release
    - git push --follow-tags origin HEAD:master
    - npm publish
